name: GitHub Pages

on:
  schedule:    
    - cron: "0 14 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.x
    - run: go run . > dist/index.html
      env:
        OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
        LOCATION: "Australia/Melbourne"
        LAT: "-37.840935"
        LONG: "144.946457"
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: qoomon/deploy-to-github-pages-action@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}